// Minimilistic/prayukt-website/src/pages/Investors.jsx
import './Investors.css';

function Investors() {
  return (
    <div className="investors">
      {/* Hero Section */}
      <section className="page-hero">
        <div className="page-hero-container">
          <h1 className="page-title fade-in">
            Investor <span className="gradient-text">Relations</span>
          </h1>
          <p className="page-subtitle">
            Delivering sustainable value through strategic growth and operational excellence
          </p>
        </div>
      </section>

      {/* Financial Highlights */}
      <section className="financial-section">
        <div className="financial-container">
          <span className="section-tag">Financial Highlights</span>
          <h2 className="section-title">Strong Performance, Sustainable Growth</h2>
          
          <div className="financial-grid">
            <div className="financial-card">
              <div className="financial-icon">📈</div>
              <div className="financial-value">$5.2B</div>
              <div className="financial-label">Annual Revenue</div>
              <div className="financial-change positive">+12% YoY</div>
            </div>
            <div className="financial-card">
              <div className="financial-icon">💰</div>
              <div className="financial-value">$850M</div>
              <div className="financial-label">Operating Profit</div>
              <div className="financial-change positive">+15% YoY</div>
            </div>
            <div className="financial-card">
              <div className="financial-icon">📊</div>
              <div className="financial-value">16.3%</div>
              <div className="financial-label">Operating Margin</div>
              <div className="financial-change positive">+1.2pp</div>
            </div>
            <div className="financial-card">
              <div className="financial-icon">💎</div>
              <div className="financial-value">$8.5B</div>
              <div className="financial-label">Market Cap</div>
              <div className="financial-change positive">+18% YoY</div>
            </div>
          </div>
        </div>
      </section>

      {/* Reports & Filings */}
      <section className="reports-section">
        <div className="reports-container">
          <div className="reports-content">
            <span className="section-tag">Resources</span>
            <h2 className="section-title">
              Reports & <span className="gradient-text">Filings</span>
            </h2>
            <p className="section-description">
              Access our latest financial reports, presentations, and regulatory filings
            </p>
          </div>

          <div className="reports-grid">
            <div className="report-card">
              <div className="report-header">
                <h3>Annual Report 2024</h3>
                <span className="report-badge">Latest</span>
              </div>
              <p className="report-description">
                Our comprehensive annual report covering financial performance, strategy, 
                and outlook for the year ahead.
              </p>
              <div className="report-footer">
                <span className="report-date">March 2024</span>
                <a href="#" className="report-link">Download PDF →</a>
              </div>
            </div>

            <div className="report-card">
              <div className="report-header">
                <h3>Q4 2024 Results</h3>
                <span className="report-badge new">New</span>
              </div>
              <p className="report-description">
                Quarterly financial results and management discussion for Q4 2024
              </p>
              <div className="report-footer">
                <span className="report-date">February 2024</span>
                <a href="#" className="report-link">Download PDF →</a>
              </div>
            </div>

            <div className="report-card">
              <div className="report-header">
                <h3>ESG Report 2024</h3>
              </div>
              <p className="report-description">
                Our environmental, social, and governance commitments and progress
              </p>
              <div className="report-footer">
                <span className="report-date">January 2024</span>
                <a href="#" className="report-link">Download PDF →</a>
              </div>
            </div>

            <div className="report-card">
              <div className="report-header">
                <h3>Investor Presentation</h3>
              </div>
              <p className="report-description">
                Latest investor presentation and strategic overview
              </p>
              <div className="report-footer">
                <span className="report-date">March 2024</span>
                <a href="#" className="report-link">Download PDF →</a>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stock Information */}
      <section className="stock-section">
        <div className="stock-container">
          <span className="section-tag">Stock Information</span>
          <h2 className="section-title">Prayukt Stock Performance</h2>
          
          <div className="stock-details">
            <div className="stock-card">
              <div className="stock-label">Exchange</div>
              <div className="stock-value">NYSE</div>
            </div>
            <div className="stock-card">
              <div className="stock-label">Ticker Symbol</div>
              <div className="stock-value">PRKT</div>
            </div>
            <div className="stock-card">
              <div className="stock-label">Current Price</div>
              <div className="stock-value">$124.50</div>
            </div>
            <div className="stock-card">
              <div className="stock-label">52 Week Range</div>
              <div className="stock-value">$98 - $135</div>
            </div>
          </div>

          <div className="stock-chart">
            <div className="chart-placeholder">
              <p>Stock price chart visualization</p>
              <span>5 Year Performance: +145%</span>
            </div>
          </div>
        </div>
      </section>

      {/* Dividend Information */}
      <section className="dividend-section">
        <div className="dividend-container">
          <div className="dividend-grid">
            <div className="dividend-info">
              <span className="section-tag">Dividends</span>
              <h2 className="section-title">Consistent Dividend Growth</h2>
              <p className="section-description">
                Prayukt has a strong track record of returning value to shareholders 
                through consistent dividend growth over the past 15 years.
              </p>
              <div className="dividend-stats">
                <div className="dividend-stat">
                  <div className="dividend-stat-value">$2.45</div>
                  <div className="dividend-stat-label">Annual Dividend per Share</div>
                </div>
                <div className="dividend-stat">
                  <div className="dividend-stat-value">1.97%</div>
                  <div className="dividend-stat-label">Dividend Yield</div>
                </div>
                <div className="dividend-stat">
                  <div className="dividend-stat-value">15</div>
                  <div className="dividend-stat-label">Years of Growth</div>
                </div>
              </div>
            </div>
            <div className="dividend-calendar">
              <h3>Upcoming Dividend Dates</h3>
              <div className="calendar-item">
                <span className="calendar-label">Ex-Dividend Date</span>
                <span className="calendar-date">May 15, 2024</span>
              </div>
              <div className="calendar-item">
                <span className="calendar-label">Record Date</span>
                <span className="calendar-date">May 17, 2024</span>
              </div>
              <div className="calendar-item">
                <span className="calendar-label">Payment Date</span>
                <span className="calendar-date">June 1, 2024</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Contact IR */}
      <section className="ir-contact-section">
        <div className="ir-contact-container">
          <h2 className="section-title">Investor Relations Contact</h2>
          <p className="section-description">
            Our investor relations team is here to assist you
          </p>
          <div className="contact-cards">
            <div className="contact-card">
              <h3>General Inquiries</h3>
              <p>Email: ir@prayukt.com</p>
              <p>Phone: +1 (555) 123-4567</p>
            </div>
            <div className="contact-card">
              <h3>Press & Media</h3>
              <p>Email: press@prayukt.com</p>
              <p>Phone: +1 (555) 123-4568</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export default Investors;

// Simplistic/src/pages/Investors.vue
<template>
  <div class="investors">
    <!-- Hero Section -->
    <section class="page-hero gradient-bg">
      <div class="container">
        <h1 class="page-title fade-in">Investor Relations</h1>
        <p class="page-subtitle fade-in">Transparent communication, sustainable growth, consistent returns</p>
      </div>
    </section>

    <!-- Financial Highlights -->
    <section class="section highlights">
      <div class="container">
        <h2 class="section-title">Financial Highlights 2024</h2>
        <div class="highlights-grid">
          <div class="card highlight-card fade-in">
            <div class="highlight-icon">📈</div>
            <div class="highlight-value">$125M</div>
            <div class="highlight-label">Revenue</div>
            <div class="highlight-change positive">+28% YoY</div>
          </div>
          <div class="card highlight-card fade-in" style="animation-delay: 0.1s">
            <div class="highlight-icon">💰</div>
            <div class="highlight-value">$32M</div>
            <div class="highlight-label">EBITDA</div>
            <div class="highlight-change positive">+35% YoY</div>
          </div>
          <div class="card highlight-card fade-in" style="animation-delay: 0.2s">
            <div class="highlight-icon">📊</div>
            <div class="highlight-value">25.6%</div>
            <div class="highlight-label">Operating Margin</div>
            <div class="highlight-change positive">+3.2 pts</div>
          </div>
          <div class="card highlight-card fade-in" style="animation-delay: 0.3s">
            <div class="highlight-icon">🎯</div>
            <div class="highlight-value">$45M</div>
            <div class="highlight-label">Free Cash Flow</div>
            <div class="highlight-change positive">+42% YoY</div>
          </div>
        </div>
      </div>
    </section>

    <!-- Latest Reports -->
    <section class="section reports">
      <div class="container">
        <h2 class="section-title">Latest Reports & Presentations</h2>
        <div class="reports-grid">
          <div class="card report-card fade-in">
            <div class="report-type">📄</div>
            <h3>Q4 2024 Earnings Report</h3>
            <p class="report-date">February 15, 2025</p>
            <p class="report-description">Complete financial results and business update for Q4 2024</p>
            <a href="#" class="btn btn-secondary">Download PDF</a>
          </div>
          <div class="card report-card fade-in" style="animation-delay: 0.1s">
            <div class="report-type">📊</div>
            <h3>Annual Report 2024</h3>
            <p class="report-date">January 30, 2025</p>
            <p class="report-description">Full year financial statements and strategic review</p>
            <a href="#" class="btn btn-secondary">Download PDF</a>
          </div>
          <div class="card report-card fade-in" style="animation-delay: 0.2s">
            <div class="report-type">🎤</div>
            <h3>Investor Presentation</h3>
            <p class="report-date">December 10, 2024</p>
            <p class="report-description">Strategy update and market outlook presentation</p>
            <a href="#" class="btn btn-secondary">Download PDF</a>
          </div>
        </div>
      </div>
    </section>

    <!-- Stock Information -->
    <section class="section stock-info gradient-bg">
      <div class="container">
        <h2 class="section-title white">Stock Information</h2>
        <div class="stock-grid">
          <div class="stock-card fade-in">
            <div class="stock-detail">
              <span class="label">Stock Symbol</span>
              <span class="value">AMPY</span>
            </div>
            <div class="stock-detail">
              <span class="label">Exchange</span>
              <span class="value">NASDAQ</span>
            </div>
            <div class="stock-detail">
              <span class="label">Current Price</span>
              <span class="value">$78.45</span>
            </div>
            <div class="stock-detail">
              <span class="label">52 Week Range</span>
              <span class="value">$52.30 - $82.90</span>
            </div>
            <div class="stock-detail">
              <span class="label">Market Cap</span>
              <span class="value">$2.8B</span>
            </div>
            <div class="stock-detail">
              <span class="label">Dividend Yield</span>
              <span class="value">2.4%</span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Calendar -->
    <section class="section calendar">
      <div class="container">
        <h2 class="section-title">Investor Calendar</h2>
        <div class="calendar-grid">
          <div class="card calendar-card fade-in">
            <div class="calendar-date">
              <div class="month">MAR</div>
              <div class="day">15</div>
            </div>
            <div class="calendar-details">
              <h3>Q1 2025 Earnings Release</h3>
              <p>Financial results announcement followed by conference call</p>
              <a href="#" class="calendar-link">Add to Calendar →</a>
            </div>
          </div>
          <div class="card calendar-card fade-in" style="animation-delay: 0.1s">
            <div class="calendar-date">
              <div class="month">APR</div>
              <div class="day">22</div>
            </div>
            <div class="calendar-details">
              <h3>Annual Shareholders Meeting</h3>
              <p>Virtual and in-person attendance available</p>
              <a href="#" class="calendar-link">Register →</a>
            </div>
          </div>
          <div class="card calendar-card fade-in" style="animation-delay: 0.2s">
            <div class="calendar-date">
              <div class="month">MAY</div>
              <div class="day">08</div>
            </div>
            <div class="calendar-details">
              <h3>Technology Summit Presentation</h3>
              <p>Executive leadership presenting at industry conference</p>
              <a href="#" class="calendar-link">Learn More →</a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Corporate Governance -->
    <section class="section governance">
      <div class="container">
        <h2 class="section-title">Corporate Governance</h2>
        <div class="governance-grid">
          <div class="card governance-card fade-in">
            <h3>Board of Directors</h3>
            <p>Independent and diverse board providing strategic oversight</p>
            <a href="#" class="learn-more">View Members →</a>
          </div>
          <div class="card governance-card fade-in" style="animation-delay: 0.1s">
            <h3>Governance Documents</h3>
            <p>Charter, policies, and compliance documentation</p>
            <a href="#" class="learn-more">Access Documents →</a>
          </div>
          <div class="card governance-card fade-in" style="animation-delay: 0.2s">
            <h3>Ethics & Compliance</h3>
            <p>Our commitment to ethical business practices</p>
            <a href="#" class="learn-more">Learn More →</a>
          </div>
          <div class="card governance-card fade-in" style="animation-delay: 0.3s">
            <h3>ESG Initiatives</h3>
            <p>Environmental, social, and governance programs</p>
            <a href="#" class="learn-more">Read Report →</a>
          </div>
        </div>
      </div>
    </section>

    <!-- Contact -->
    <section class="section contact gradient-bg">
      <div class="container">
        <div class="contact-content fade-in">
          <h2>Investor Relations Contact</h2>
          <div class="contact-details">
            <div class="contact-item">
              <strong>Email:</strong>
              <a href="mailto:ir@amplify.com">ir@amplify.com</a>
            </div>
            <div class="contact-item">
              <strong>Phone:</strong>
              <a href="tel:+15551234567">+1 (555) 123-4567</a>
            </div>
            <div class="contact-item">
              <strong>Address:</strong>
              <span>123 Innovation Drive, Tech City, TC 12345</span>
            </div>
          </div>
          <button class="btn btn-light">Email IR Team</button>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
export default {
  name: 'Investors'
}
</script>

<style scoped>
.page-hero {
  padding: 150px 0 100px;
  text-align: center;
}

.page-title {
  font-size: 56px;
  color: white;
  margin-bottom: 20px;
}

.page-subtitle {
  font-size: 22px;
  color: rgba(255, 255, 255, 0.9);
}

.highlights {
  background: var(--primary-black);
  padding: 80px 0;
}

.highlights-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 30px;
  margin-top: 60px;
}

.highlight-card {
  text-align: center;
  padding: 40px;
}

.highlight-icon {
  font-size: 48px;
  margin-bottom: 16px;
}

.highlight-value {
  font-size: 42px;
  font-weight: 800;
  color: var(--deep-brown);
  margin-bottom: 8px;
  text-shadow: 0 0 20px rgba(160, 122, 88, 0.3);
}

.highlight-label {
  font-size: 16px;
  color: var(--text-light);
  margin-bottom: 12px;
}

.highlight-change {
  font-size: 14px;
  font-weight: 600;
  padding: 6px 12px;
  border-radius: 20px;
  display: inline-block;
}

.highlight-change.positive {
  background: rgba(46, 204, 113, 0.1);
  color: #2ECC71;
}

.reports {
  background: var(--primary-black);
  padding: 80px 0;
}

.reports-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 30px;
  margin-top: 60px;
}

.report-card {
  padding: 40px;
}

.report-type {
  font-size: 56px;
  margin-bottom: 20px;
}

.report-card h3 {
  font-size: 24px;
  margin-bottom: 8px;
  color: var(--deep-brown);
}

.report-date {
  color: var(--accent-gold);
  font-weight: 600;
  margin-bottom: 16px;
}

.report-description {
  color: var(--text-light);
  line-height: 1.6;
  margin-bottom: 24px;
}

.stock-info {
  padding: 80px 0;
}

.stock-grid {
  margin-top: 60px;
  max-width: 800px;
  margin-left: auto;
  margin-right: auto;
}

.stock-card {
  background: rgba(255, 255, 255, 0.15);
  backdrop-filter: blur(10px);
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-radius: 20px;
  padding: 40px;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 30px;
}

.stock-detail {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.stock-detail .label {
  color: rgba(255, 255, 255, 0.8);
  font-size: 14px;
}

.stock-detail .value {
  color: white;
  font-size: 24px;
  font-weight: 700;
}

.calendar {
  background: var(--primary-black);
  padding: 80px 0;
}

.calendar-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
  gap: 30px;
  margin-top: 60px;
}

.calendar-card {
  display: grid;
  grid-template-columns: 100px 1fr;
  gap: 24px;
  padding: 30px;
}

.calendar-date {
  text-align: center;
  background: var(--accent-gold);
  color: var(--off-white);
  border-radius: 12px;
  padding: 16px;
  height: fit-content;
}

.month {
  font-size: 14px;
  font-weight: 600;
  margin-bottom: 4px;
}

.day {
  font-size: 32px;
  font-weight: 800;
}

.calendar-details h3 {
  font-size: 20px;
  margin-bottom: 8px;
  color: var(--deep-brown);
}

.calendar-details p {
  color: var(--text-light);
  line-height: 1.6;
  margin-bottom: 12px;
}

.calendar-link {
  color: var(--deep-brown);
  font-weight: 600;
  transition: color 0.3s ease;
}

.calendar-link:hover {
  color: var(--accent-gold);
}

.governance {
  background: var(--primary-black);
  padding: 80px 0;
}

.governance-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 30px;
  margin-top: 60px;
}

.governance-card {
  padding: 40px;
  text-align: center;
}

.governance-card h3 {
  font-size: 22px;
  margin-bottom: 16px;
  color: var(--deep-brown);
}

.governance-card p {
  color: var(--text-light);
  line-height: 1.6;
  margin-bottom: 20px;
}

.learn-more {
  color: var(--deep-brown);
  font-weight: 600;
  transition: color 0.3s ease;
}

.learn-more:hover {
  color: var(--accent-gold);
}

.contact {
  padding: 80px 0;
}

.contact-content {
  text-align: center;
  max-width: 600px;
  margin: 0 auto;
}

.contact-content h2 {
  font-size: 42px;
  color: white;
  margin-bottom: 40px;
}

.contact-details {
  display: flex;
  flex-direction: column;
  gap: 20px;
  margin-bottom: 40px;
}

.contact-item {
  display: flex;
  flex-direction: column;
  gap: 8px;
  color: white;
}

.contact-item strong {
  font-size: 14px;
  opacity: 0.8;
}

.contact-item a,
.contact-item span {
  font-size: 18px;
  color: white;
  font-weight: 600;
}

.contact-item a {
  transition: opacity 0.3s ease;
}

.contact-item a:hover {
  opacity: 0.8;
}

@media (max-width: 768px) {
  .page-title {
    font-size: 38px;
  }

  .calendar-card {
    grid-template-columns: 1fr;
  }

  .stock-card {
    grid-template-columns: 1fr;
  }
}
</style>
